version: "3.8"
services:
    app:
        image: dockerdemodb:0.0.1
        environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/student
        - SPRING_DATASOURCE_USERNAME=admin
        - SPRING_DATASOURCE_PASSWORD=root
        depends_on:
        - db
        ports:
        - "9090:8083" # Expose port 8080 to access the Java app


    db:
        image: mysql:8.0
        environment:
          DATABASE_HOST: db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: student
          MYSQL_USER: admin
          MYSQL_PASSWORD: root
        ports:
        - "3307:3306" # Expose port 3306 for MySQL access


